[tool.isort]
profile = "black"

[tool.ruff]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
]
ignore = [
    "E203",  # whitespace-before-punctuation
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
]
unfixable = [
    "B"  # flake8-bugbear
]

[tool.ruff.per-file-ignores]
"__init__.py" = [
    "E402",  # module-import-not-at-top-of-file
    "F401"  # Module imported but unused
]

[tool.ruff.isort]
known-third-party = ["fastapi", "pydantic", "starlette"]

[tool.mypy]
# strict = true
warn_unused_ignores = true
ignore_missing_imports = true
plugins = "pydantic.mypy"

[tool.coverage.report]
exclude_lines = [
    "def __repr__",
    "if TYPE_CHECKING:",
]
