"""add_credit_card

Revision ID: ba7f94858bd1
Revises: 9337a241a3cc
Create Date: 2025-01-21 20:47:59.856638

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.config import settings
from app.models.encrypted import Encrypted

# revision identifiers, used by Alembic.
revision: str = "ba7f94858bd1"
down_revision: str | None = "9337a241a3cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_credit_cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("credit_card", Encrypted(settings.ENCRYPTION_KEY), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_credit_cards")
    # ### end Alembic commands ###
